# Site settings
title: Club Robotique ENET'COM
email: robotic.club.enetcom@gmail.com
description: Dream - Believe - Achieve
baseurl: ""
url: ""

facebook_username: CR.ENETCOM
instagram_username: CR.ENETCOM
phone_number: +21655452950

# Build settings
markdown: kramdown
