# Site settings
title: Club Robotique ENET'COM
email: robotic.club.enetcom@gmail.com
description: Dream - Believe - Achieve
baseurl: ""
url: ""

twitter_username:
github_username:

# Build settings
markdown: kramdown
